#!/bin/bash
# Canonical PPO training launcher (foreground + artifact logging).

set -euo pipefail

usage() {
  cat <<'EOF'
Usage: ./start_ppo_training.sh [options] [-- <extra OpenVLA_PPO.py args>]

Options:
  --task-suite <name>        LIBERO suite (default: libero_spatial)
  --task-id <id>             Single task id (default: 0)
  --timesteps <n>            Total timesteps (default: 10000000)
  --seed <n>                 Random seed (default: 0)
  --warmup-min-steps <n>     Min BC warmup steps before RL handoff (default: 25000)
  --warmup-max-steps <n>     Warmup safety cap; <=0 disables (default: 32000)
  --warmup-success-thresh <x>
                             Rolling tokenized success threshold (default: 0.40)
  --warmup-success-window <n>
                             Validation window for rolling success (default: 3)
  --warmup-success-consec <n>
                             Consecutive validations above threshold (default: 2)
  --warmup-overclone-thresh <x>
                             Immediate handoff threshold to avoid over-cloning (default: 0.85)
  --entropy-coef <x>         RL entropy bonus coefficient (default: 0.002)
  --pretrained-checkpoint <ref>
                             Checkpoint ref (default: openvla-7b-oft-finetuned-libero-spatial)
  --use-hf-checkpoint        Load checkpoint from HuggingFace Hub (default: local)
  --resume-checkpoint <path> Resume from a previous training checkpoint (.pt)
  --resume-stage <mode>      Stage after resume: auto|warmup|rl (default: rl when resuming)
  --cuda-devices <list>      CUDA_VISIBLE_DEVICES (default: 0,1)
  --run-name <name>          Artifact run name (default: autogenerated)
  --log-root <dir>           Root log dir (default: artifacts/logs)
  --checkpoint-root <dir>    Root checkpoint dir (default: artifacts/checkpoints)
  --wandb-entity <name>      Optional wandb entity/team
  --no-wandb                 Disable wandb logging
  --no-data-parallel         Disable DataParallel flag
  --dry-run                  Print resolved command and exit
  -h, --help                 Show help
EOF
}

TASK_SUITE="libero_spatial"
TASK_ID=0
TIMESTEPS=10000000
SEED=0
WARMUP_MIN_STEPS=25000
WARMUP_MAX_STEPS=32000
WARMUP_SUCCESS_THRESH=0.40
WARMUP_SUCCESS_WINDOW=3
WARMUP_SUCCESS_CONSEC=2
WARMUP_OVERCLONE_THRESH=0.85
ENTROPY_COEF=0.002
PRETRAINED_CHECKPOINT="openvla-7b-oft-finetuned-libero-spatial"
USE_HF_CHECKPOINT=0
RESUME_CHECKPOINT=""
RESUME_STAGE="auto"
CUDA_DEVICES="0,1"
RUN_NAME=""
LOG_ROOT="artifacts/logs"
CHECKPOINT_ROOT="artifacts/checkpoints"
WANDB_ENTITY=""
USE_WANDB=1
USE_DATA_PARALLEL=1
DRY_RUN=0
EXTRA_ARGS=()

while [[ $# -gt 0 ]]; do
  case "$1" in
    --task-suite) TASK_SUITE="$2"; shift 2 ;;
    --task-id) TASK_ID="$2"; shift 2 ;;
    --timesteps) TIMESTEPS="$2"; shift 2 ;;
    --seed) SEED="$2"; shift 2 ;;
    --warmup-min-steps) WARMUP_MIN_STEPS="$2"; shift 2 ;;
    --warmup-max-steps) WARMUP_MAX_STEPS="$2"; shift 2 ;;
    --warmup-success-thresh) WARMUP_SUCCESS_THRESH="$2"; shift 2 ;;
    --warmup-success-window) WARMUP_SUCCESS_WINDOW="$2"; shift 2 ;;
    --warmup-success-consec) WARMUP_SUCCESS_CONSEC="$2"; shift 2 ;;
    --warmup-overclone-thresh) WARMUP_OVERCLONE_THRESH="$2"; shift 2 ;;
    --entropy-coef) ENTROPY_COEF="$2"; shift 2 ;;
    --pretrained-checkpoint) PRETRAINED_CHECKPOINT="$2"; shift 2 ;;
    --use-hf-checkpoint) USE_HF_CHECKPOINT=1; shift ;;
    --resume-checkpoint) RESUME_CHECKPOINT="$2"; shift 2 ;;
    --resume-stage) RESUME_STAGE="$2"; shift 2 ;;
    --cuda-devices) CUDA_DEVICES="$2"; shift 2 ;;
    --run-name) RUN_NAME="$2"; shift 2 ;;
    --log-root) LOG_ROOT="$2"; shift 2 ;;
    --checkpoint-root) CHECKPOINT_ROOT="$2"; shift 2 ;;
    --wandb-entity) WANDB_ENTITY="$2"; shift 2 ;;
    --no-wandb) USE_WANDB=0; shift ;;
    --no-data-parallel) USE_DATA_PARALLEL=0; shift ;;
    --dry-run) DRY_RUN=1; shift ;;
    -h|--help) usage; exit 0 ;;
    --) shift; EXTRA_ARGS+=("$@"); break ;;
    *) EXTRA_ARGS+=("$1"); shift ;;
  esac
done

if [[ -n "$RESUME_CHECKPOINT" && "$RESUME_STAGE" == "auto" ]]; then
  # Common case: reuse a completed warmup checkpoint and jump straight to RL.
  RESUME_STAGE="rl"
fi

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
if [[ -z "$RUN_NAME" ]]; then
  RUN_NAME="ppo_${TASK_SUITE}_task${TASK_ID}_seed${SEED}_$(date +%Y%m%d_%H%M%S)"
fi

LOG_DIR="$REPO_ROOT/$LOG_ROOT"
CHECKPOINT_DIR="$REPO_ROOT/$CHECKPOINT_ROOT/$RUN_NAME"
LOG_FILE="$LOG_DIR/${RUN_NAME}.log"

export CUDA_VISIBLE_DEVICES="$CUDA_DEVICES"
export PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True

CMD=(
  python OpenVLA_PPO.py
  --task-suite "$TASK_SUITE"
  --task-id "$TASK_ID"
  --timesteps "$TIMESTEPS"
  --seed "$SEED"
  --warmup-min-steps "$WARMUP_MIN_STEPS"
  --warmup-max-steps "$WARMUP_MAX_STEPS"
  --warmup-success-threshold "$WARMUP_SUCCESS_THRESH"
  --warmup-success-window "$WARMUP_SUCCESS_WINDOW"
  --warmup-success-consecutive "$WARMUP_SUCCESS_CONSEC"
  --warmup-overclone-threshold "$WARMUP_OVERCLONE_THRESH"
  --entropy-coef "$ENTROPY_COEF"
  --pretrained-checkpoint "$PRETRAINED_CHECKPOINT"
  --checkpoint-dir "$CHECKPOINT_DIR"
)
if [[ $USE_HF_CHECKPOINT -eq 1 ]]; then
  CMD+=(--use-hf-checkpoint)
fi
if [[ -n "$RESUME_CHECKPOINT" ]]; then
  CMD+=(--resume-checkpoint "$RESUME_CHECKPOINT" --resume-stage "$RESUME_STAGE")
fi

if [[ $USE_WANDB -eq 0 ]]; then
  CMD+=(--no-wandb)
fi
if [[ -n "$WANDB_ENTITY" ]]; then
  CMD+=(--wandb-entity "$WANDB_ENTITY")
fi
if [[ $USE_DATA_PARALLEL -eq 1 ]]; then
  CMD+=(--use-data-parallel)
fi
if [[ ${#EXTRA_ARGS[@]} -gt 0 ]]; then
  CMD+=("${EXTRA_ARGS[@]}")
fi

if [[ $DRY_RUN -eq 1 ]]; then
  echo "========================================="
  echo "PPO Training Launcher (dry-run)"
  echo "========================================="
  echo "Repo root: $REPO_ROOT"
  echo "Run name: $RUN_NAME"
  echo "Log file: $LOG_FILE"
  echo "Checkpoint dir: $CHECKPOINT_DIR"
  echo "CUDA_VISIBLE_DEVICES: $CUDA_VISIBLE_DEVICES"
  printf 'Command: '
  printf '%q ' "${CMD[@]}"
  printf '\n'
  echo "Dry run requested; exiting before creating artifact directories."
  exit 0
fi

mkdir -p "$LOG_DIR" "$CHECKPOINT_DIR"

# Mirror launcher + training output to file and terminal.
exec > >(tee -a "$LOG_FILE") 2>&1

echo "========================================="
echo "PPO Training Launcher"
echo "========================================="
echo "Repo root: $REPO_ROOT"
echo "Run name: $RUN_NAME"
echo "Log file: $LOG_FILE"
echo "Checkpoint dir: $CHECKPOINT_DIR"
echo "CUDA_VISIBLE_DEVICES: $CUDA_VISIBLE_DEVICES"

cd "$REPO_ROOT"

echo ""
echo "========================================="
echo "Starting PPO Training (foreground)"
echo "========================================="
printf 'Command: '
printf '%q ' "${CMD[@]}"
printf '\n'
echo ""

echo "Activating conda environment..."
source ~/miniconda3/etc/profile.d/conda.sh
conda activate oft_rl
echo "Using Python: $(which python)"
echo "Python version: $(python --version)"

echo ""
echo "GPU Status:"
nvidia-smi --query-gpu=index,name,memory.used,memory.total --format=csv,noheader 2>/dev/null || echo "Could not query GPU"

"${CMD[@]}"
